name: fcbaz
description: FCBaz - Persian FUTBIN-style companion with free real data
publish_to: "none"
version: 1.0.6+7

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/fcbaz_app_icon.png
    - assets/data/players_fc26.json.gz
    - assets/data/free_content.json

flutter_launcher_icons:
  android: true
  image_path: assets/icon/fcbaz_app_icon.png
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: assets/icon/fcbaz_app_icon.png
  remove_alpha_ios: true
