-- FCBaz cloud sync + FCM device registry
-- Run in Supabase SQL editor for the production project.

create table if not exists public.fcbaz_user_sync (
  user_id uuid primary key references auth.users(id) on delete cascade,
  snapshot jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.fcbaz_devices (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  token text not null unique,
  platform text not null default 'android',
  updated_at timestamptz not null default now()
);

create index if not exists fcbaz_devices_user_id_idx
  on public.fcbaz_devices(user_id);

alter table public.fcbaz_user_sync enable row level security;
alter table public.fcbaz_devices enable row level security;

-- App requests go through the FCBaz backend. The backend uses the service role,
-- so no direct public table policies are required.


create table if not exists public.fcbaz_push_alert_state (
  user_id uuid not null references auth.users(id) on delete cascade,
  player_id text not null,
  target_price bigint not null,
  reached boolean not null default false,
  last_price bigint,
  updated_at timestamptz not null default now(),
  primary key (user_id, player_id, target_price)
);

alter table public.fcbaz_push_alert_state enable row level security;
